project:
  type: website

website:
  title: "Group 8 Project: VAST Challenge 2025 Mini-Challenge 3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Communication Patterns Analysis/Proposal.qmd
        text: Proposal
      - href: xxx.qmd
        text: Poster
      - href: xxx.qmd
        text: Meeting Minutes
      - text: Shiny
        menu:
          - text: User Guide
            href: xxx.qmd
          - text: Shiny App
            href: https://hjportfolio.shinyapps.io/Group8ProjectVASTChallenge2025MiniChallenge3/
      - text: GitHub
        menu:
          - text: Project Repo
            href: https://github.com/CHJ1/G8ProjectFolder
          - text: Shiny Repo
            href: https://github.com/CHJ1/G8ProjectFolder/tree/main/ShinyApp
      - href: about.qmd
        text: About Us

format:
  html:
    theme: Minty
    css: styles.css
    toc: true

editor: visual

