project:
  type: website

website:
  title: "Group 8 Project: VAST Challenge 2025 Mini-Challenge 3"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
      
  sidebar:
    - id: main
      title: "Navigation"
      style: "docked"
      contents:
        - index.qmd
        - text: "Communication Patterns Analysis"
          href: Communication Patterns Analysis.qmd
        - text: "Clustering"
          href: "xxx.html"

format:
  html:
    theme: Minty
    css: styles.css
    toc: true

editor: visual

