project:
  type: website

website:
  title: "G8ProjectFolder"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    - id: main
      title: "Navigation"
      style: "docked"
      contents:
        - index.qmd
        - about.qmd

format:
  html:
    theme: Minty
    css: styles.css
    toc: true

editor: visual

