project:
  type: website

website:
  title: "Group 8 Project: VAST Challenge 2025 Mini-Challenge 3"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
      
  sidebar:
    - id: main
      title: "Navigation"
      style: "docked"
      contents:
        - index.qmd
        - text: "Communication Patterns Analysis"
          href: Test copy.qmd
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"

format:
  html:
    theme: Minty
    css: styles.css
    toc: true

editor: visual

